version: '3.9'
services:

  #database service
  weshopify-platform-db-service: 
   container_name: weshopify-platform-db
   image: mysql
   restart: always
   ports:
     - 3306:3306
   environment: 
    - MYSQL_DATABASE=weshopify-app
    - MYSQL_ROOT_PASSWORD=root
   volumes:
     - /opt/weshopify-db-data:/var/lib/mysql
   

  #app service  
  weshopify-platform-app-service: 
    #container_name: weshopify-platform-app
    image: weshopify-backend-app-img
    restart: on-failure
    ports:
      #- 8082:8082
      - "8082-8085:8082"
    environment: 
     - DB_HOST=weshopify-platform-db-service
     - DB_SCHEMA=weshopify-app 